### ISSUE TITLE
Cannot create new network with zncstrap?

### ISSUE THREAD

**Issue by jesseleite** [ProjectFirrre/zncstrap#18]
I am having trouble creating new network with zncstrap web interface.  I get this: http://puu.sh/gjoTS/f2ae37632c.png

It works if I put original modules and webskins folders back though.  Bug?

**Comment by sprybear** [comment]
Howdy, JerseyMilker,

Mind asking, which version of ZNC and zncstrap branch are you currently utilizing?

Well, let's assume, you're utilizing v1.6 stable or either the git version. If so, you will need to utilize the 'dev' branch files instead, as both branches varies; different 'name' attributes (as pointed below). Otherwise, if you're on ZNC v1.4, kindly utilize the 'master' branch.

Differences:
- master branch: https://github.com/ProjectFirrre/zncstrap/blob/master/modules/webadmin/tmpl/add_edit_network.tmpl#L19
- dev branch: https://github.com/ProjectFirrre/zncstrap/blob/dev/modules/webadmin/tmpl/add_edit_network.tmpl#L33

If the issue still persists, do tell. I'll try to replicate it on my end and we'll go from there.

**Comment by jesseleite** [comment]
Ahh maybe that's the issue.  Thanks I'll give that a try.

**Comment by jesseleite** [comment]
Seems to be working, sorry for my incompetence and lack of reading :P
